# basic options
title: Online Portfolio
author: Sean Johnson
email: gy19saj@leeds.ac.uk
description: An online portfolio of specific projects completed as part of the GIS MSc course at the University of Leeds
github_username:  Seanj15
titles_from_headings:
  enabled:     false
  strip_title: true
  
 

# Build settings
markdown: kramdown
theme: minima
