# basic options
title: Online Portfolio
author: Sean Johnson
email: gy19saj@leeds.ac.uk
description: An online portfolio of specific coding-based projects
github_username:  Seanj15
defaults:
  - scope:
      path: some-path
      layout: some_layout
    values:
      strip_title: true
 

# Build settings
markdown: kramdown
theme: minima
